name: "Dune builder"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  builder:

    name: DuneBuilder

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dune
        uses: nmittu/setup-dune@v2
        with:
          packages: "coq"

      - name: Add MMaps
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install coq-mmaps

      - name: build
        run: |
          eval $(opam config env)
          dune build